// File generated by FlutterFire CLI.

// Ignore lint warnings for this generated configuration file.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Stores Firebase configuration options for each supported platform.
class DefaultFirebaseOptions {
  // Returns the Firebase configuration for the current platform.
  static FirebaseOptions get currentPlatform {
    // Web is not configured for this application.
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }

    // Select the appropriate Firebase configuration based on the platform.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // Return the Android Firebase configuration.
        return android;

      case TargetPlatform.iOS:
        // Return the iOS Firebase configuration.
        return ios;

      case TargetPlatform.macOS:
        // macOS is not configured for this application.
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.windows:
        // Windows is not configured for this application.
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.linux:
        // Linux is not configured for this application.
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        // Handle unsupported platforms.
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration for the Android application.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFWpBED-6kHEHz48gNStKIUMwFryIOuJE',
    appId: '1:255504828226:android:0cd19043f463d89940eadb',
    messagingSenderId: '255504828226',
    projectId: 'fypautochat',
    storageBucket: 'fypautochat.firebasestorage.app',
  );

  // Firebase configuration for the iOS application.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD65z2QW-XKSeW3haRouR55kf2Huo8mHRM',
    appId: '1:255504828226:ios:985d1d0d2af44ebc40eadb',
    messagingSenderId: '255504828226',
    projectId: 'fypautochat',
    storageBucket: 'fypautochat.firebasestorage.app',
    iosBundleId: 'com.example.autosecurechat',
  );
}
